# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/graph-ml',
                'doc_host': 'https://jdbergren@gmail.com.github.io',
                'git_url': 'https://github.com/jdbergren@gmail.com/graph-ml',
                'lib_path': 'graph_ml'},
  'syms': {'graph_ml.core': {'graph_ml.core.foo': ('core.html#foo', 'graph_ml/core.py')}}}
